title: My Fitness Story
email: xuanmy289@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal space where I share my journey in Pilates.
baseurl: "/skills-github-pages"
url: "https://mybuixuan.github.io"

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed